#!/bin/sh

PMOS_DIR=/sda17p2/pmos

for MP in /dev /proc /sys; do
  mount -o bind ${MP} "${PMOS_DIR}"${MP}
done

mount /dev/mapper/sda17p1 "${PMOS_DIR}"/boot

mount -o bind /etc/resolv.conf "${PMOS_DIR}"/etc/resolv.conf 

chroot "${PMOS_DIR}" "${@}"

umount "${PMOS_DIR}"/etc/resolv.conf

umount "${PMOS_DIR}"/boot

for MP in /sys /proc /dev; do
  umount "${PMOS_DIR}"${MP}
done