# Use Fedora Base Image
FROM registry.fedoraproject.org/fedora:latest

# Instal DNF5 as it is much more performant
RUN dnf install -y dnf5 dnf5-plugins
RUN dnf5 install -y dnf5 dnf5-plugins 

# Enable justinz/op6 Copr
RUN dnf install -y 'dnf-command(copr)'
RUN dnf copr enable -y justinz/op6

# Install Plasma Mobile Packages
RUN dnf5 install -y kscreen \
                    maliit-keyboard \
                    plasma-mobile \
                    sddm

# Install Plasma Mobile Apps Packages
RUN dnf5 install -y \
                           angelfish \
                           bluedevil \
                           calindori \
                           elisa-player \
                           kalk \
                           kclock \
                           koko \
                           kf5-kirigami2-addons \
                           plasma-dialer \
                           plasma-discover \
                           plasma-nm-mobile \
                           plasma-phonebook \
                           plasma-settings \
                           qmlkonsole \
                           spacebar

# Install Tool Packages
RUN dnf5 install -y nano \
                    openssh-server \
                    util-linux \
                    util-linux-user

# Install SDM845 Packages
RUN dnf5 install -y pd-mapper \
                   qbootctl \
                   rmtfs \
                   tqftpserv

# Install Network Packages
RUN dnf5 install -y iproute \
                    iputils \
                    NetworkManager-bluetooth \
                    NetworkManager-config-connectivity-fedora \
                    NetworkManager-wifi \
                    NetworkManager-wwan \
                    wireless-regdb \
                    wpa_supplicant

# Setup Group/User/PIN
RUN groupadd -g 1000 user && \
  useradd -g 1000 -G wheel -m -u 1000 user && \
  echo 'user:147147' | chpasswd

# Set Boot Device
RUN echo '/dev/mapper/sda17p2 / ext4 rw,relatime 0 0' > /etc/fstab

# Enable Systemd Services
RUN systemctl enable pd-mapper \
                     qbootctl-mark-boot-successful \
                     rmtfs \
                     sddm \
                     sshd \
                     tqftpserv

# Setup Autologin in SDDM
RUN cp files/autologin.conf /etc/sddm.conf.d/autologin.conf

# Setup Default Browser and Look and Feel
RUN cp files/kdeglobals /etc/xdg/kdeglobals

# Setup Auto Screen Lock on Login
RUN cp files/kscreenlockerrc /etc/xdg/kscreenlockerrc

# Set Virtual Keyboard to Maliit
RUN cp files/kwinrc /etc/xdg/kwinrc

ENTRYPOINT ["/bin/bash", "-l", "-i"]
