FROM registry.fedoraproject.org/fedora:latest

RUN dnf upgrade -y --refresh
RUN dnf install -y dnf5 dnf5-plugins

RUN dnf5 install -y \
  systemd \
  systemd-udev

RUN dnf5 install -y \
  'dnf-command(copr)' \
  tmux vim

RUN dnf5 remove -y 'plymouth*'

COPY fstab /etc/fstab
RUN install -d -o 0 -g 0 -m 0755 /sda17p2

COPY hostname /etc/hostname

RUN dnf5 install -y openssh-server && \
  systemctl enable sshd

RUN dnf5 install -y pd-mapper rmtfs qrtr 
RUN dnf copr enable -y ryanabx/op6

# RUN dnf5 install -y device-oneplus-enchilada
# Install copr packages
RUN dnf5 install -y qbootctl

RUN systemctl enable pd-mapper
RUN systemctl enable qbootctl-mark-boot-successful.service
# RUN systemctl enable tqftpserv
RUN systemctl enable rmtfs

# RUN /usr/bin/pmos-chroot-setup
# RUN /usr/bin/pmos-adopt-and-integrate

RUN echo 'root:654321' | chpasswd 

RUN groupadd -g 1000 unpriv && \
  useradd -g 1000 -G wheel -m -u 1000 unpriv && \
  echo 'unpriv:123456' | chpasswd

# Install Plasma Mobile
RUN dnf5 install -y plasma-mobile plasma-nano qmlkonsole angelfish plasma-dialer plasma-phonebook spacebar kscreen sddm maliit-keyboard kf5-kirigami2-addons plasma-settings bluedevil elisa-player plasma-discover

# Install tools
RUN dnf5 install -y util-linux lshw lsusb pciutils nano htop screen iproute wpa_supplicant NetworkManager-tui iw iputils wireless-regdb dhcp-client NetworkManager-wifi NetworkManager-wwan NetworkManager-bluetooth

RUN systemctl enable sddm

# Setup Autologin in SDDM
RUN echo '[Autologin]' > /etc/sddm.conf.d/autologin.conf && \
    echo 'User=user' >> /etc/sddm.conf.d/autologin.conf && \
    echo 'Session=plasma-mobile' >> /etc/sddm.conf.d/autologin.conf

# Setup Default Browser and Look and Feel
RUN echo '# SPDX-FileCopyrightText: None' > /etc/xdg/kdeglobals && \
    echo '# SPDX-License-Identifier: CC0-1.0' >> /etc/xdg/kdeglobals && \
    echo '[General]' >> /etc/xdg/kdeglobals && \
    echo 'BrowserApplication[$e]=!angelfish' >> /etc/xdg/kdeglobals && \
    echo '[KDE]' >> /etc/xdg/kdeglobals && \
    echo 'LookAndFeelPackage=org.kde.plasma.phone' >> /etc/xdg/kdeglobals

# Setup Auto Screen Lock on Login
RUN echo '# SPDX-FileCopyrightText: None' > /etc/xdg/kscreenlockerrc && \
    echo '# SPDX-License-Identifier: CC0-1.0' >> /etc/xdg/kscreenlockerrc && \
    echo '[Daemon]' >> /etc/xdg/kscreenlockerrc && \
    echo 'LockOnStart=true' >> /etc/xdg/kscreenlockerrc

# Set Virtual Keyboard to Maliit
RUN echo '[Wayland]' > /etc/xdg/kwinrc && \
    echo 'InputMethod[$e]=/usr/share/applications/com.github.maliit.keyboard.desktop' >> /etc/xdg/kwinrc && \
    echo 'VirtualKeyboardEnabled=true' >> /etc/xdg/kwinrc

ENTRYPOINT ["/bin/bash", "-l", "-i"]

