FROM docker.io/maggu2810/op6-fedora:latest

# Install Plasma Mobile
RUN dnf5 install -y plasma-mobile plasma-nano qmlkonsole angelfish plasma-dialer plasma-phonebook spacebar kscreen sddm maliit-keyboard kf5-kirigami2-addons plasma-settings bluedevil elisa-player plasma-discover

# Install tools
RUN dnf5 install -y util-linux lshw lsusb pciutils nano htop screen iproute wpa_supplicant NetworkManager-tui iw iputils wireless-regdb dhcp-client NetworkManager-wifi NetworkManager-wwan NetworkManager-bluetooth

RUN systemctl enable sddm

# Setup Autologin in SDDM
RUN echo '[Autologin]' > /etc/sddm.conf.d/autologin.conf && \
    echo 'User=user' >> /etc/sddm.conf.d/autologin.conf && \
    echo 'Session=plasma-mobile' >> /etc/sddm.conf.d/autologin.conf

# Setup Default Browser and Look and Feel
RUN echo '# SPDX-FileCopyrightText: None' > /etc/xdg/kdeglobals && \
    echo '# SPDX-License-Identifier: CC0-1.0' >> /etc/xdg/kdeglobals && \
    echo '[General]' >> /etc/xdg/kdeglobals && \
    echo 'BrowserApplication[$e]=!angelfish' >> /etc/xdg/kdeglobals && \
    echo '[KDE]' >> /etc/xdg/kdeglobals && \
    echo 'LookAndFeelPackage=org.kde.plasma.phone' >> /etc/xdg/kdeglobals

# Setup Auto Screen Lock on Login
RUN echo '# SPDX-FileCopyrightText: None' > /etc/xdg/kscreenlockerrc && \
    echo '# SPDX-License-Identifier: CC0-1.0' >> /etc/xdg/kscreenlockerrc && \
    echo '[Daemon]' >> /etc/xdg/kscreenlockerrc && \
    echo 'LockOnStart=true' >> /etc/xdg/kscreenlockerrc

# Set Virtual Keyboard to Maliit
RUN echo '[Wayland]' > /etc/xdg/kwinrc && \
    echo 'InputMethod[$e]=/usr/share/applications/com.github.maliit.keyboard.desktop' >> /etc/xdg/kwinrc && \
    echo 'VirtualKeyboardEnabled=true' >> /etc/xdg/kwinrc

ENTRYPOINT ["/bin/bash", "-l", "-i"]

